### ISSUE TITLE
LazyJsonMapper Error

### ISSUE THREAD

**Issue by yusufusta** [ffb255/botter#2]
OS: Ubuntu 16.04
PHP Version: 7.4

I'm using example code.

Error:
`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to LazyJsonMapper\LazyJsonMapper::__construct() must be of the type array, null given, called in /root/turklirasi/vendor/ffb255/botter/src/BotterFactory.php on line 38 and defined in /root/turklirasi/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php:683
Stack trace:
#0 /root/turklirasi/vendor/ffb255/botter/src/BotterFactory.php(38): LazyJsonMapper\LazyJsonMapper->__construct()
#1 /root/turklirasi/bot.php(7): ffb255\Botter\BotterFactory::create()
#2 {main}
  thrown in /root/turklirasi/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php on line 683`

**Comment by ff4m1r** [comment]
Currently Botter only works with webhook. So please set a webhook for your bot, then use Botter.
Long-Polling will be added soon.
